"""Grounded generation: founder narratives (six themes, per the paper) and
free-form Q&A. Every context chunk gets a citation tag [S1]..[Sn] so the UI
can trace each statement back to its source — an upgrade over the paper,
which reported source grounding but did not surface inline citations.
"""
from __future__ import annotations

import re

from .llm import LLMUnavailable
from .prompts import ANSWER_SYSTEM as _ANSWER_SYSTEM
from .prompts import NARRATIVE_SYSTEM as _NARRATIVE_SYSTEM
from .retrieval import tokenize


def _format_context(chunks: list[dict]) -> str:
    lines = []
    for i, chunk in enumerate(chunks, 1):
        lines.append(
            f"[S{i}] (source: {chunk['source_title']}, {chunk['source_type']}, "
            f"founder: {chunk['founder']})\n{chunk['text']}"
        )
    return "\n\n".join(lines)


def citation_map(chunks: list[dict]) -> list[dict]:
    return [
        {
            "tag": f"S{i}",
            "chunk_id": chunk["id"],
            "source_title": chunk["source_title"],
            "source_type": chunk["source_type"],
            "founder": chunk["founder"],
        }
        for i, chunk in enumerate(chunks, 1)
    ]


def generate_narrative(llm, founder: str, company: str, chunks: list[dict]) -> str:
    context = _format_context(chunks)
    if llm.mode == "claude":
        try:
            return llm.complete(
                system=_NARRATIVE_SYSTEM,
                user=(
                    f"Founder: {founder} ({company}).\n\nContext passages:\n\n{context}"
                ),
                max_tokens=10000,
            )
        except LLMUnavailable:
            pass
    return _offline_narrative(founder, company, chunks)


def generate_answer(llm, question: str, chunks: list[dict]) -> str:
    context = _format_context(chunks)
    if llm.mode == "claude":
        try:
            return llm.complete(
                system=_ANSWER_SYSTEM,
                user=f"Question: {question}\n\nContext passages:\n\n{context}",
                max_tokens=4000,
            )
        except LLMUnavailable:
            pass
    return _offline_answer(question, chunks)


# --- offline extractive fallbacks ------------------------------------------

_THEME_KEYWORDS = {
    "Founder and Company": ["founder", "founded", "co-founded", "ceo", "company", "startup"],
    "Timeline of Critical Events": ["in 19", "in 20", "year", "launched", "started", "began", "became"],
    "Key Success Markers": ["raised", "million", "billion", "customers", "profitable", "valuation", "unicorn", "users"],
    "Ecosystem Influences and Interactions": ["mentor", "accelerator", "network", "partner", "investor", "diaspora"],
    "Challenges and Resilience": ["challenge", "difficult", "struggle", "regulat", "overcame", "failed", "hurdle"],
    "Impact on the Ecosystem": ["jobs", "impact", "trained", "inclusion", "policy", "community", "inspired"],
}


def _sentences_with_tags(chunks: list[dict]) -> list[tuple[str, str]]:
    out = []
    for i, chunk in enumerate(chunks, 1):
        for sent in re.split(r"(?<=[.!?])\s+", chunk["text"]):
            sent = sent.strip()
            if len(sent.split()) >= 6:
                out.append((sent, f"S{i}"))
    return out


def _offline_narrative(founder: str, company: str, chunks: list[dict]) -> str:
    tagged = _sentences_with_tags(chunks)
    parts = [
        "> _Generated by the offline extractive engine (no LLM credentials). "
        "Sentences are selected verbatim from retrieved sources._",
        f"\n## Founder and Company\n{founder}, associated with {company}. [S1]"
        if chunks else "\n## Founder and Company\nNo relevant information in the retrieved context.",
    ]
    used: set[str] = set()
    for section, keywords in list(_THEME_KEYWORDS.items())[1:]:
        picks = []
        for sent, tag in tagged:
            lower = sent.lower()
            if sent in used:
                continue
            if any(k in lower for k in keywords):
                picks.append(f"- {sent} [{tag}]")
                used.add(sent)
            if len(picks) >= 5:
                break
        body = "\n".join(picks) if picks else "No relevant information in the retrieved context."
        parts.append(f"\n## {section}\n{body}")
    return "\n".join(parts)


def _offline_answer(question: str, chunks: list[dict]) -> str:
    q_tokens = set(tokenize(question))
    scored = []
    seen: set[str] = set()
    for sent, tag in _sentences_with_tags(chunks):
        if sent in seen:  # chunk overlap repeats boundary sentences
            continue
        seen.add(sent)
        overlap = len(q_tokens & set(tokenize(sent)))
        if overlap:
            scored.append((overlap, sent, tag))
    scored.sort(key=lambda t: -t[0])
    if not scored:
        return "The retrieved context does not contain an answer to this question."
    lines = ["_Offline extractive answer (no LLM credentials) — most relevant sentences:_", ""]
    for _, sent, tag in scored[:5]:
        lines.append(f"- {sent} [{tag}]")
    return "\n".join(lines)
